DROP TABLE "MSG";
DROP TABLE "NOTICE";
DROP TABLE "BOARD_LIKE";
DROP TABLE "BOARD_IMG";
DROP TABLE "REPLY";
DROP TABLE "BOARD";
DROP TABLE "MEMBER";
--  MEMBER 시퀀스
DROP SEQUENCE SEQ_USER_NO;
CREATE SEQUENCE SEQ_USER_NO;
--  BOARD 시퀀스
DROP SEQUENCE SEQ_BOARD_NO;
CREATE SEQUENCE SEQ_BOARD_NO;
--  REPLY 시퀀스
DROP SEQUENCE SEQ_REPLY_NO;
CREATE SEQUENCE SEQ_REPLY_NO;
--  REPLY 시퀀스
DROP SEQUENCE SEQ_BOARD_IMG_NO;
CREATE SEQUENCE SEQ_BOARD_IMG_NO;
--  NOTICE 시퀀스
DROP SEQUENCE SEQ_NOTICE_NO;
CREATE SEQUENCE SEQ_NOTICE_NO;
--  NOTICE 시퀀스
DROP SEQUENCE SEQ_MSG_NO;
CREATE SEQUENCE SEQ_MSG_NO;
-- 회원 테이블
CREATE TABLE MEMBER(
    USER_NO NUMBER PRIMARY KEY,
    USER_ID VARCHAR2(12) NOT NULL,
    USER_PWD VARCHAR2(100) NOT NULL,
    NICK_NAME VARCHAR2(30) NOT NULL,
    NAME VARCHAR2(20) NOT NULL,
    AGE NUMBER NOT NULL,
    EMAIL VARCHAR2(50) NOT NULL,
    PHONE CHAR(11) NOT NULL,
    ADDRESS VARCHAR2(300) NOT NULL,
    GENDER CHAR(3) NOT NULL CHECK(GENDER IN('남', '여')), 
    CHANGE_NAME VARCHAR2(100) DEFAULT NULL,
    CREATE_DATE DATE DEFAULT SYSDATE,
    MODIFY_DATE DATE DEFAULT SYSDATE,
    MSG_STATUS CHAR(1) DEFAULT 'Y' CHECK(MSG_STATUS IN('Y','N')),
    STATUS CHAR(1) DEFAULT 'Y' CHECK(STATUS IN('Y','N'))
);


COMMENT ON COLUMN MEMBER.USER_NO IS '사용자번호';
COMMENT ON COLUMN MEMBER.USER_ID IS '아이디';
COMMENT ON COLUMN MEMBER.USER_PWD IS '비밀번호';
COMMENT ON COLUMN MEMBER.NICK_NAME IS '닉네임';
COMMENT ON COLUMN MEMBER.NAME IS '이름';
COMMENT ON COLUMN MEMBER.AGE IS '나이';
COMMENT ON COLUMN MEMBER.EMAIL IS '이메일';
COMMENT ON COLUMN MEMBER.PHONE IS '전화번호';
COMMENT ON COLUMN MEMBER.ADDRESS IS '주소';
COMMENT ON COLUMN MEMBER.GENDER IS '성별';
COMMENT ON COLUMN MEMBER.CHANGE_NAME IS '파일명 및 경로';
COMMENT ON COLUMN MEMBER.CREATE_DATE IS '회원가입일';
COMMENT ON COLUMN MEMBER.MODIFY_DATE IS '회원정보수정일';
COMMENT ON COLUMN MEMBER.MSG_STATUS IS '채팅메세지여부';
COMMENT ON COLUMN MEMBER.STATUS IS '탈퇴여부';
INSERT INTO "MEMBER"(
        USER_NO,
        USER_ID,
        USER_PWD,
        NICK_NAME,
        NAME,
        AGE,
        EMAIL,
        PHONE,
        ADDRESS,
        GENDER
        )
VALUES(
SEQ_USER_NO.NEXTVAL,
'admin',
'admin',
'관리자',
'관리자',
20,
'asd@gmail.com',
'01012345678',
'가디랑 구디 사이',
'남'
);
-- 여행 후기 게시판 테이블
CREATE TABLE BOARD(
    BOARD_NO NUMBER PRIMARY KEY,
    BOARD_TITLE VARCHAR2(100) NOT NULL,
    BARD_CONTENT VARCHAR2(300) NOT NULL,
    CREATE_DATE DATE DEFAULT SYSDATE,
    COUNT NUMBER DEFAULT 0,
    STATUS CHAR(1) DEFAULT 'Y' CHECK(STATUS IN('Y','N')),
    USER_NO NUMBER,
    FOREIGN KEY(USER_NO) REFERENCES MEMBER(USER_NO)
);
COMMENT ON COLUMN BOARD.BOARD_NO IS '여행후기게시글번호';
COMMENT ON COLUMN BOARD.BOARD_TITLE IS '제목';
COMMENT ON COLUMN BOARD.BARD_CONTENT IS '내용';
COMMENT ON COLUMN BOARD.CREATE_DATE IS '작성일';
COMMENT ON COLUMN BOARD.COUNT IS '조회수';
COMMENT ON COLUMN BOARD.STATUS IS '게시글 상태';
-- 여행 후기 게시판 댓글 테이블
CREATE TABLE REPLY(
    RB_REPLY_NO NUMBER PRIMARY KEY,
    PB_CONTENT VARCHAR2(300) NOT NULL,
    CREATE_DATE DATE DEFAULT SYSDATE,
    MODIFY_DATE DATE,
    USER_NO NUMBER,
    BOARD_NO NUMBER,
    FOREIGN KEY(USER_NO) REFERENCES MEMBER(USER_NO),
    FOREIGN KEY(BOARD_NO) REFERENCES BOARD(BOARD_NO)
);
COMMENT ON COLUMN REPLY.RB_REPLY_NO IS '댓글번호';
COMMENT ON COLUMN REPLY.PB_CONTENT IS '댓글 내용';
COMMENT ON COLUMN REPLY.CREATE_DATE IS '댓글 작성일';
COMMENT ON COLUMN REPLY.MODIFY_DATE IS '댓글 수정일';
-- 여행 후기 게시판 이미지 테이블
CREATE TABLE BOARD_IMG(
    IMG_NO NUMBER PRIMARY KEY,
    CHANGE_NAME VARCHAR2(100) NOT NULL,
    FILE_LEVEL CHAR(1) NOT NULL CHECK(FILE_LEVEL IN(1, 2)),
    STATUS CHAR(1) DEFAULT 'Y' CHECK(STATUS IN('Y', 'N')),
    BOARD_NO NUMBER,
    FOREIGN KEY(BOARD_NO) REFERENCES BOARD(BOARD_NO)
);
COMMENT ON COLUMN BOARD_IMG.IMG_NO IS '후기게시판 이미지번호';
COMMENT ON COLUMN BOARD_IMG.CHANGE_NAME IS '파일명 및 경로';
COMMENT ON COLUMN BOARD_IMG.FILE_LEVEL IS '썸네일 여부';
COMMENT ON COLUMN BOARD_IMG.STATUS IS '이미지 상태';
-- 여행 후기 게시판 좋아요 테이블
CREATE TABLE BOARD_LIKE(
    USER_NO NUMBER,
    BOARD_NO NUMBER,
    FOREIGN KEY(USER_NO) REFERENCES MEMBER(USER_NO),
    FOREIGN KEY(BOARD_NO) REFERENCES BOARD(BOARD_NO)
);
-- 공지사항 테이블
CREATE TABLE NOTICE(
    NOTICE_NO NUMBER PRIMARY KEY,
    NOTICE_TITLE VARCHAR2(100) NOT NULL,
    NOTICE_CONTENT VARCHAR2(300) NOT NULL,
    CHANGE_NAME VARCHAR2(100),
    CREATE_DATE DATE DEFAULT SYSDATE,
    STATUS CHAR(1) DEFAULT 'Y' CHECK(STATUS IN('Y', 'N'))
);
COMMENT ON COLUMN NOTICE.NOTICE_NO IS '공지사항 번호';
COMMENT ON COLUMN NOTICE.NOTICE_TITLE IS '공지사항 제목';
COMMENT ON COLUMN NOTICE.NOTICE_CONTENT IS '내용';
COMMENT ON COLUMN NOTICE.CHANGE_NAME IS '파일명 및 경로';
COMMENT ON COLUMN NOTICE.CREATE_DATE IS '공지사항 작성일';
COMMENT ON COLUMN NOTICE.STATUS IS '공지사항 글 상태';
-- 채팅 테이블
CREATE TABLE MSG(
    MSG_NO NUMBER PRIMARY KEY,
    MSG_CONTENT VARCHAR2(600) NOT NULL,
    MSG_TIME DATE DEFAULT SYSDATE,
    USER_NO NUMBER,
    FOREIGN KEY(USER_NO) REFERENCES MEMBER(USER_NO)
);
COMMENT ON COLUMN MSG.MSG_NO IS '채팅 번호';
COMMENT ON COLUMN MSG.MSG_CONTENT IS '채팅 내용';
COMMENT ON COLUMN MSG.MSG_TIME IS '채팅 시간';
COMMIT;
INSERT INTO NOTICE(
NOTICE_NO,
NOTICE_TITLE,
NOTICE_CONTENT,
CHANGE_NAME
)
VALUES(
SEQ_NOTICE_NO.NEXTVAL,
'첫 번째 공지사항',
'집가고싶다',
'resources/image/am.jpg'
);
commit;